### ISSUE TITLE
Suggestions to expand the usage scenarios and clarify how to use Miniapp Widget

### ISSUE THREAD

**Issue by Sharonzd** [w3c/miniapp-widget#2]
1. I understand that the MiniApp Widget spec will standardize a special presentation of MiniApp. The MiniApp Widget should not be limited to mobile os(smart assistant), but also be displayed on any MiniApp platforms such as IoT devices and host Apps. 

2. There is no description about how MiniApp developers can develop MiniApp widget in the requirement. Maybe we should add interface descriptions and more use cases to show that the presentation and  development of the MiniApp widget.

**Comment by xfq** [comment]
Related discussions: https://www.w3.org/2021/05/20-MiniApp-minutes.html#t04

**Comment by maxie** [comment]
Agree. I'll add more use cases on more examples of MiniApp platforms (more types of smart devices and super apps). 

About 2nd point, i think in most time, MiniApp widget is launched by host app, instead of developer. Maybe i can add some details about this part.

**Comment by xfq** [comment]
Closing per https://www.w3.org/2021/12/16-miniapp-minutes.html#t02
