### ISSUE TITLE
Update the URI in the explainer

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-widget#5]
https://github.com/w3c/miniapp-widget/blob/main/docs/explainer.md#addressing-url

The URI in the explainer needs to be updated to conform to the new version of the [Addressing](https://w3c.github.io/miniapp-addressing/) spec.

**Comment by Sharonzd** [comment]
yeah, the [sample code](https://github.com/w3c/miniapp-widget/blob/main/docs/explainer.md#addressing-url)
`miniapp://foo;version=1.0.1-trial@example.com:8080/widgets/index?k=v#bar`
should change to 
`platform://miniapp/foo;version=1.0.1-trial/pages/index?k=v#bar
or
https://platform.org/miniapp/foo;version=1.0.1-trial/pages/index?k=v#bar`

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/miniapp-widget/commit/4dd69bed42444d6f8b79d08cdcb33ebe75c90258
